### ISSUE TITLE
npm ERR! fetch failed https://registry.npmjs.org/html-minifier/-/html-minifier-3.2.0.tgz

### ISSUE THREAD

**Issue by inversion** [kangax/html-minifier#745]
Might be an intermittent NPM server issue, but is the published package definitely valid?

*edit*: As other people have said if your transitive dependencies' semver specifications for html-minifier will match 3.1.1 you can add "html-minifier": "3.1.1", to your package.json dependencies to work around this, and if you are using html-minifier directly this workaround also applies.

**Comment by inversion** [comment]
https://github.com/npm/npm/wiki/Troubleshooting#not-found--server-error

**Comment by alexlamsl** [comment]
I just published it <10 minutes ago - so may be wait for a bit? :stuck_out_tongue_winking_eye:

**Comment by jdrydn** [comment]
Oh good, I'm happy I'm not the only one experiencing this!

**Comment by pgetta** [comment]
Same here, hope this will be resolved fast

**Comment by jdrydn** [comment]
Obviously, it goes without saying, if you're happy to miss out on this update (for now) there's always `npm install html-minifier@3.1.1`

**Comment by inversion** [comment]
@jdrydn transitive dependencies 😢 

edit: could override with shrinkwrap but waiting is lazier ;)

edit: as other people have said if the dependencies' semver specifications for html-minifier will match 3.1.1 you can add `"html-minifier": "3.1.1",` to your package.json dependencies

**Comment by kronicker** [comment]
Same here, waiting... :sleeping: :smile:

**Comment by alexlamsl** [comment]
I run into that myself as well, but given I had to play a game of patience with Travis CI earlier today I guess I can give it another hour before I look into this further.

**Comment by phiphou** [comment]
Same as everybody here,  how many time do you think we have to wait ?

**Comment by codechaotic** [comment]
@jdrydn your suggestion did the trick for me. Installed `3.1.1` first and then ran `npm install` after it. The install used the older version to satisfy transitive dependencies. Thanks.

**Comment by Canos** [comment]
I was trying to a new project, i got the message while installing angular-cli, can anybody provide a workaround please? 
Installing 3.1.1 is not a workaround, angular-cli requires html-minifier.
Thanks

**Comment by rosko** [comment]
I use `react-styleguidist`, which uses `html-webpack-plugin`, which uses `html-minifier`. Travis CI fails.

**Comment by joshwiens** [comment]
Same issue here. It's a dependency of a dependency and I'm sitting on  my hands at the moment :(

**Comment by DomenicRoti** [comment]
For a temp fix though this in your package.json:
`"html-minifier": "3.1.1",`

**Comment by rosko** [comment]
@alexlamsl please, just publish a new patch version to npm

**Comment by joshwiens** [comment]
@rosko - @DomenicRoti is correct, install that as a devDep and you can get past the build errors

**Comment by MohammedSiddiqui** [comment]
Makes you wonder how fragile all of this is ... _waiting_

**Comment by codechaotic** [comment]
Even if it's a dependency of a dependency downgrading to `3.1.1` is still an option. Npm's dependency resolution algorithm allows this as long as you either install the older version first (so it's available during `npm install`), or explicitly state the version in your package.json as @DomenicRoti suggested.

**Comment by danielsamuels** [comment]
Yup, our builds just started failing. Installing through Yarn FWIW.

**Comment by jdrydn** [comment]
> Installing 3.1.1 is not a workaround, angular-cli requires html-minifier.

@Canos: Before `3.2.0` was pushed, `angular-cli` would have installed `3.1.1`

**Comment by DomenicRoti** [comment]
If you specify it in your package.json (as 3.1.1) then when you do an npm install, it won't try to install 3.2.0 for Angular-Cli, it will use the version the specified in your package.json

**Comment by rosko** [comment]
Is it too hard for the maintainers to run `npm version patch && npm publish`?...

**Comment by rosko** [comment]
Thank you, guys!

**Comment by alexlamsl** [comment]
Published `3.2.1` and works on my end - so should be fixed for everyone now.

**Comment by luzzardi** [comment]
Still not working for me

npm ERR! fetch failed https://registry.npmjs.org/html-minifier/-/html-minifier-3.2.1.tgz

**Comment by meeksfred** [comment]
Still not working for me either.

npm ERR! fetch failed https://registry.npmjs.org/html-minifier/-/html-minifier-3.2.1.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 404

**Comment by rosko** [comment]
It works for me... strange

**Comment by danielsamuels** [comment]
Probably needs to propagate to local CDNs?

**Comment by nesheroj** [comment]
Same here, forcing to use 3.1.1 works but this is going to break many CI's

**Comment by phiphou** [comment]
DNS progagation make take some times no ? So, depending from where you are...

**Comment by rosko** [comment]
very strange... it works locally for me, but doesn't work on TravisCI

**Comment by phiphou** [comment]
Works for me (France) locally, not tested on CircleCI yet, I'll let you know.

**Comment by alexlamsl** [comment]
Funny that... I tried it three times and the third attempt failed with a 404. Then now I can't get `3.2.1` anymore.

In either case, I don't think I can do much as it's a `npm` issue obviously.

**Comment by alexlamsl** [comment]
I have hacked around a bit and `npm unpublish` both `3.2.1` and `3.2.0` - so we are now back on `3.1.1` for the time being.

And I shall wait for `npm` to sort itself out before publishing the latest version. Sorry about the trouble!

**Comment by soldair** [comment]
im looking into this please track this at the issue created by @heatmonkey
https://github.com/npm/registry/issues/85

**Comment by alexlamsl** [comment]
3.2.2 is now published and should hopefully be working for everybody.

**Comment by timeapen** [comment]
Is this really fixed?  I think we have some kind of transitive dependency that is looking for 3.2.0, so our build is failing.  Also, if I execute a `npm view html-minifier versions` I don't even see 3.2.2.

```
'3.0.0',
  '3.0.1',
  '3.0.2',
  '3.0.3',
  '3.1.0',
  '3.1.1',
  '3.2.0' ]
```

**Comment by phiphou** [comment]
Yes it is :

``` bash
$ npm view html-minifier versions

[ ... ,
  '3.0.2',
  '3.0.3',
  '3.1.0',
  '3.1.1',
  '3.2.2' ]
```
